"""types_changing

Revision ID: 6ae7b48b8185
Revises: c1a7f4f1130d
Create Date: 2024-10-14 11:47:56.185731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae7b48b8185'
down_revision: Union[str, None] = 'c1a7f4f1130d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE assettype AS ENUM ('crypto', 'stock', 'fiat')")
    op.execute("CREATE TYPE transactiontype AS ENUM ('buy', 'sell')")

    op.drop_column('transactions', 'total_price')

    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('crypto', 'stock', 'fiat', name='assettype'),
               existing_nullable=False,
               postgresql_using="asset_type::assettype")
    op.alter_column('portfolio_assets', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('buy', 'sell', name='transactiontype'),
               existing_nullable=False,
               postgresql_using="transaction_type::transactiontype")
    op.alter_column('transactions', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    op.alter_column('portfolios', 'total_invested',
                    existing_type=sa.INTEGER(),
                    type_=sa.FLOAT(),
                    existing_nullable=False)

    op.alter_column('portfolios', 'current_value',
                    existing_type=sa.INTEGER(),
                    type_=sa.FLOAT(),
                    existing_nullable=False)

    op.add_column('transactions', sa.Column('total_price', sa.Float(),
                                            sa.Computed("quantity * price")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_price')

    op.alter_column('transactions', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum('buy', 'sell', name='transactiontype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('portfolio_assets', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.Enum('crypto', 'stock', 'fiat', name='assettype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.alter_column('portfolios', 'total_invested',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('portfolios', 'current_value',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)

    op.add_column('transactions', sa.Column('total_price', sa.Integer(),
                                            sa.Computed('quantity * price')))

    op.execute("DROP TYPE transactiontype")
    op.execute("DROP TYPE assettype")
    # ### end Alembic commands ###
