"""cascade deleting

Revision ID: c341d34bbe0f
Revises: 6ae7b48b8185
Create Date: 2024-10-16 14:04:57.089163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c341d34bbe0f'
down_revision: Union[str, None] = '6ae7b48b8185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('portfolio_assets_portfolio_id_fkey', 'portfolio_assets', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_assets', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('portfolios_user_id_fkey', 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_portfolio_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_portfolio_id_fkey', 'transactions', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key('portfolios_user_id_fkey', 'portfolios', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'portfolio_assets', type_='foreignkey')
    op.create_foreign_key('portfolio_assets_portfolio_id_fkey', 'portfolio_assets', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###
